### PR TITLE
Refactor/polymorphic tests

### LINKED ISSUE #16: Polymorphic tests
What should be done:
- improve package exports reducing import path down to @packageName
- fix latency naming convention
- add configurable and default rpcTimeout
- refactor tests
- create test specific esbuild env

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/ubiquity/rpc-handler/issues/16

Split from #6 

Required by #14

### CODE REVIEW

**Comment by Keyrxng** [comment]
the jest workflow shouldn't run `yarn build` only `yarn test` which builds for testing

**Comment by Keyrxng** [comment]
CI is failing here because it's using workflows from `development` I'm sure

image

Testing it myself my CI keeps throwing this below but as you can see above all test cases are passing, I just need to figure out why my CI seems to be busted. Lots of related gh issues for it, tried a fair few solutions to no avail, yet.

image

**Comment by rndquu** [comment]
@Keyrxng 
1. Pls update readme
2. Check this code:
```
import { HandlerConstructorConfig } from "./dist";
import { RPCHandler } from "./dist";

const config: HandlerConstructorConfig = {
    networkId: 1,
    autoStorage: false,
  };

async function main() {
    const handler = new RPCHandler(config);
    const provider = await handler.getFastestRpcProvider();
    console.log(provider.connection);
    console.log('success');
}

main();

```

The code above produces this error:
```
(node:14881) TimeoutOverflowWarning: 1.7976931348623157e+308 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
[RPCService] Failed to find fastest RPC
/Users/rndquu/Public/projects/backend/rpc-handler/dist/index.js:17021
      throw new Error("Failed to find fastest RPC");
            ^

Error: Failed to find fastest RPC
    at _RPCHandler.testRpcPerformance (/Users/rndquu/Public/projects/backend/rpc-handler/dist/index.js:17021:13)
    at async _RPCHandler.getFastestRpcProvider (/Users/rndquu/Public/projects/backend/rpc-handler/dist/index.js:17001:24)
    at main (/Users/rndquu/Public/projects/backend/rpc-handler/my.ts:11:22)

```

Pls fix

**Comment by Keyrxng** [comment]
You should only need to fill in the required config props and your golden. I fresh installed, tried both build envs with your script and with `tests/script-test.ts`

```ts
const config: HandlerConstructorConfig = {
  networkId: 1,
  rpcTimeout: 1500,
  autoStorage: false,
  cacheRefreshCycles: 10,
  networkName: null,
  networkRpcs: null,
  runtimeRpcs: null,
};
```

**Comment by rndquu** [comment]
@Keyrxng Why did you remove `yarn.lock` completely?

**Comment by rndquu** [comment]
@Keyrxng Could you merge https://github.com/Keyrxng/web3-rpc-racer-1/pull/3 ?

**Comment by Keyrxng** [comment]
because of the CI errors I was having seeing as the fresh lock didn't change anything and typically no lock is committed. 

Think it's best to add it back?

**Comment by rndquu** [comment]
@Keyrxng Could you describe the main code changes of this exact PR and provide a time estimate for it?

**Comment by rndquu** [comment]
> @Keyrxng Could you describe the main code changes of this exact PR and provide a time estimate for it?

P.S. [Tests](https://github.com/ubiquity/rpc-handler/actions/runs/9172207708/job/25218203769?pr=15) seems to be passing + the package works fine

**Comment by Keyrxng** [comment]
- improve package exports reducing import path down to `@packageName`
- fix latency naming convention
- add configurable and default rpcTimeout
- refactor tests
- create test specific esbuild env

time 2-4 hrs 

@rndquu

The task I'd say is making the package polymorphic, the latency and timeout fix happening over the course of review. Tests needed refactored because of how the way the build output was changed in improving exports.

**Comment by rndquu** [comment]
> * improve package exports reducing import path down to `@packageName`
> * fix latency naming convention
> * add configurable and default rpcTimeout
> * refactor tests
> * create test specific esbuild env
> 
> time 2-4 hrs
> 
> @rndquu
> 
> The task I'd say is making the package polymorphic, the latency and timeout fix happening over the course of review. Tests needed refactored because of how the way the build output was changed in improving exports.

Pls self assign https://github.com/ubiquity/rpc-handler/issues/16

**Pull request merged**
