### PR TITLE
Refactor/improved exports

### PR DESCRIPTION
**Pull request by Keyrxng**
Split from #6

- includes all requested changes from the linked PR related to the changes made in this PR
- fixes latency naming convention
- adds timeout
- improved type exports

### CODE REVIEW

**Comment by rndquu** [comment]
@Keyrxng Why did you close it?

**Comment by Keyrxng** [comment]
My mistake @rndquu, I thought that the one you just merged was the only one you needed

**Comment by rndquu** [comment]
@Keyrxng 

1. This PR simply removes unused files, correct?
2. Pls fix the build, the development one is [passing](https://github.com/ubiquity/rpc-handler/actions/runs/9172675101)

**Comment by Keyrxng** [comment]
@rndquu just knip to go now

**Comment by rndquu** [comment]
> @rndquu just knip to go now

There are 0 files changed. I don't understand what we should do with this PR.

**Comment by Keyrxng** [comment]
I created the branch from the commit where I removed the files as that was part of the improving exports, the tests included all commits from this PR which is why I closed it.

I thought I had mistakenly split a PR which shouldn't have been split and you just used the one with all of the changes, I gather I've made a couple of blunders along the way.

This can be closed since it adds nothing of value.

**Pull request closed without merging**
