### PR TITLE
rpc-handler fix knip issues

### LINKED ISSUE #12: Create correct Knip workflow and Knip configuration for rpc-handler

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves https://github.com/ubiquity/rpc-handler/issues/12

QA: https://github.com/gitcoindev/rpc-handler/actions/runs/9164829604

Knip workflow and all findings should be fixed after merging this PR. 

I removed `node-fetch` from direct dependencies as I found references only in `node_modules` transitive dependencies.

### CODE REVIEW

**Comment by gitcoindev** [comment]
@rndquu , @molecula451 I assume the failed tests were fixed in https://github.com/ubiquity/rpc-handler/pull/6 by @Keyrxng .

**Review by molecula451 — APPROVED** [review]

**Comment by rndquu** [comment]
@gitcoindev 

Could you:
1. Merge the latest `development` branch and resolve conflicts
2. Bring back the `node-fetch` package. It is used by the `lib/chainlist` github submodule [here](https://github.com/DefiLlama/chainlist/blob/b00e30a86ea131a895ece42d07a7c250bacc2243/utils/fetch.js#L3). Besides I got the build error "node-fetch is missing" without this package to be mentioned explicitly in `package.json`.

**Comment by gitcoindev** [comment]
> @gitcoindev
> 
> Could you:
> 
> 1. Merge the latest `development` branch and resolve conflicts
> 2. Bring back the `node-fetch` package. It is used by the `lib/chainlist` github submodule [here](https://github.com/DefiLlama/chainlist/blob/b00e30a86ea131a895ece42d07a7c250bacc2243/utils/fetch.js#L3). Besides I got the build error "node-fetch is missing" without this package to be mentioned explicitly in `package.json`.

@rndquu thank you for checking this. I synced my fork to the latest development branch and rebased against it, removing two commits from the pr branch. I force pushed the branch this time to avoid clutter, I would be grateful if you checked again.

**Comment by rndquu** [comment]
There is too much hurdle with knip. It doesn't work as expected. Check this ci [run](https://github.com/ubiquity/rpc-handler/actions/runs/9176339546/job/25231376647?pr=13) and these errors:
```
Unused files (2)
src/services/rpc-service.ts
src/services/storage-service.ts
```

`rpc-service.ts` and `storage-service.ts` are clearly used [here](https://github.com/ubiquity/rpc-handler/blob/e5c4a558e0862dad0a85b614904d4c54d801a271/types/rpc-handler.ts#L68) and [here](https://github.com/ubiquity/rpc-handler/blob/e5c4a558e0862dad0a85b614904d4c54d801a271/tests/mocks/rpc-handler.ts#L73).

```
Unused dependencies (2)
axios package.json
node-fetch package.json
```

`axios` is used [here](https://github.com/ubiquity/rpc-handler/blob/e5c4a558e0862dad0a85b614904d4c54d801a271/src/services/rpc-service.ts#L14).

At this point it makes sense to stop using knip and remove it completely (at least from this repo) because maintaining knip's CI workflow gets down to ignoring certain files that are definitely part of the project.

**Comment by gitcoindev** [comment]
@rndquu I have just seen it, will try to fix configuration. Once it is fixed, I do not think much maintenance will be needed.

**Comment by gitcoindev** [comment]
> @rndquu I have just seen it, will try to fix configuration. Once it is fixed, I do not think much maintenance will be needed.

I was able to reproduce and fix configuration locally, just pushed an update.

**Comment by rndquu** [comment]
@gitcoindev Do we need the following steps ([one](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR13), [two](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR17), [three](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR20), [four](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR25)) if `Knip-reporter` [workflow](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml) simply downloads and displays the results?

I'm this picky because [knip-reporter](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml) runs in a privileged context with access to org secrets (because of `on: workflow_run`) and `yarn isntall` [here](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml#L26) could be utilized to exfiltrate secrets should we miss a PR with malicious code in the `development` branch which is checked out [here](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml#L14).

**Comment by gitcoindev** [comment]
> @gitcoindev Do we need the following steps ([one](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR13), [two](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR17), [three](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR20), [four](https://github.com/ubiquity/rpc-handler/pull/13/files#diff-e300da0383d00d275266a83902a2aff8c7f62da696de4bc47ca5810e69c01ffeR25)) if `Knip-reporter` [workflow](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml) simply downloads and displays the results?
> 
> I'm this picky because [knip-reporter](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml) runs in a privileged context with access to org secrets (because of `on: workflow_run`) and `yarn isntall` [here](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml#L26) could be utilized to exfiltrate secrets should we miss a PR with malicious code in the `development` branch which is checked out [here](https://github.com/ubiquity/rpc-handler/blob/b705a36405e14e5ab9f6516316443475771a3af0/.github/workflows/knip-reporter.yml#L14).

You are picky but right. I will check this in the next 2 hours. It should be possible to skip those steps.

**Comment by gitcoindev** [comment]
All right! I was able to test this at https://github.com/gitcoindev/rpc-handler/pull/5 , will push a follow up commit asap.

**Comment by gitcoindev** [comment]
@rndquu I removed the steps at https://github.com/ubiquity/rpc-handler/pull/13/commits/759fb4d455441b4a66dc434879da113efbd66f27 , please check again.

**Comment by gitcoindev** [comment]
QA CI with steps removed: https://github.com/gitcoindev/rpc-handler/actions/runs/9178339860/job/25238013021

**Review by rndquu — APPROVED** [review]

**Comment by rndquu** [comment]
@gitcoindev Works fine, thank you

**Pull request merged**
