### PR TITLE
Added `postbuild` script to the publish workflow

### LINKED ISSUE #21: Published without types
I'm unsure what's caused this but it's been published without types.

- https://www.npmjs.com/package/@ubiquity-dao/rpc-handler?activeTab=code 

- https://www.npmjs.com/package/@keyrxng/rpc-handler?activeTab=code what it should look like

running `yarn build` then `yarn pack` followed by `tar -tf ubiquity-dao-rpc-handler-v1.1.0.tgz` locally reveals:

```bash
...
package/dist/types
package/dist/cjs/index.js
package/dist/esm/index.js
package/dist/types/constants.d.ts
package/dist/types/handler.d.ts
package/dist/types/rpc-handler.d.ts
```

Looking at the [run](https://github.com/ubiquity/rpc-handler/actions/runs/9180797875/job/25246055017) reveals:

```bash
npm notice 📦  @ubiquity-dao/rpc-handler@1.1.0
npm notice === Tarball Contents === 
npm notice 2.5kB   README.md        
npm notice 1.5MB   dist/cjs/index.js
npm notice 572.7kB dist/esm/index.js
npm notice 573.1kB dist/index.js    
npm notice 2.6kB   package.json     
npm notice === Tarball Details === 
```

Looking at both versions of the UBQ package neither has `/types` or any `d.ts` files. While all four of my versions have either `/types` or `.d.ts` files.

<hr/>

The only difference between the two workflows is `publish` is broken off into an additional step (don't see why that would affect it).

Locally the types are built as expected.

### PR DESCRIPTION
**Pull request by Sadaf-A**
Resolves #21 
This PR adds the `postbuild` script which is responsible for generating the types in the publish workflow

### CODE REVIEW

**Comment by Keyrxng** [comment]
@rndquu this likely did resolve the issue, as I'm confident the issue is with yarn V4 and having to explicitly call the pre/post scripts. 

The only thing I'm thinking is that the build flow has since changed and the current `postbuild` script removes `/dist/src` and does not build the types, so this will not resolve the issue now. #24 will change the build flow again so I'm unsure how to proceed with this PR.

I think it's best to get `Proxify` merged first and see where the chips land with it then take it from there.

**Comment by 0x4007** [comment]
> I think it's best to get `Proxify` merged first and see where the chips land with it then take it from there.

I don't have enough context on this codebase or task to offer more useful suggestions, but generally speaking,  I think its the wrong approach to ever "wait to merge" another pull. This slows down progress and people's payments. Consider merging to separate and dedicated branches to deal with merge conflicts later etc.

**Comment by Keyrxng** [comment]
@Sadaf-A considering the above, the current implementation would not resolve things.

My thinking with `Proxify` is to build the types as part of a `run-s` which should be viewed as a single script and run each stage. Since `run-s/run-p` is the general approach to yarn commands I'd test this approach first, alternatively adding each step into the workflow as you have done here should work.

Consider pulling so you are up to date then apply one of the two strategies. 

Ensure that you are using yarn V4 if you plan to test things locally such as yarn pack and inspecting the tarbell contents etc

QA may look like:
- tarbell contents via your workflow run logs (this happens automatically when its published)
- link the `#code` section on npmjs of your published QA package so this way it can be easily verified then later deleted.

An effective solution to this aims to ensure that we have `.d.ts` files in the published package via a workflow run, that is the only criteria needed to have this merged. The other contents of the package can be ignored as `Proxify` will update those.

**Comment by Sadaf-A** [comment]
@Keyrxng please have a look

**Comment by Keyrxng** [comment]
> @Keyrxng please have a look

Could you link the QA that I requested please? Looking at the changes made I am sceptical that they'd work as intended. `run-s` is a package and I'm not confident that the workflow would be able to globally access the package like that without using a package manager to invoke it, I may be mistaken so the QA would be much appreciated. Also it's more commonplace to execute a `yarn xyz` command which invokes the `run-s abc cba` script.

I see that you have tried `build postbuild`, this would not build the types looking at the `development` branch (which you should be up to date with)

What should be done:
- run the workflow from your repo ensuring it completes without failure
- verify the contents of the package via the `#code` tab on [npmjs](https://www.npmjs.com/package/@ubiquity-dao/rpc-handler?activeTab=code) and that they include `.d.ts` files then link us to the package

Thanks @Sadaf-A

**Comment by Sadaf-A** [comment]
> > @Keyrxng please have a look
> 
> Could you link the QA that I requested please? Looking at the changes made I am sceptical that they'd work as intended. `run-s` is a package and I'm not confident that the workflow would be able to globally access the package like that without using a package manager to invoke it, I may be mistaken so the QA would be much appreciated. Also it's more commonplace to execute a `yarn xyz` command which invokes the `run-s abc cba` script.
> 
> I see that you have tried `build postbuild`, this would not build the types looking at the `development` branch (which you should be up to date with)
> 
> What should be done:
> - run the workflow from your repo ensuring it completes without failure
> - verify the contents of the package via the `#code` tab on [npmjs](https://www.npmjs.com/package/@ubiquity-dao/rpc-handler?activeTab=code) and that they include `.d.ts` files then link us to the package
> 
> Thanks @Sadaf-A 

I see what you mean I will change it to `npx run-s build postbuild` and link the QA that should resolve the issue Thank You

**Comment by Sadaf-A** [comment]
> > @Keyrxng please have a look
> 
> Could you link the QA that I requested please? Looking at the changes made I am sceptical that they'd work as intended. `run-s` is a package and I'm not confident that the workflow would be able to globally access the package like that without using a package manager to invoke it, I may be mistaken so the QA would be much appreciated. Also it's more commonplace to execute a `yarn xyz` command which invokes the `run-s abc cba` script.
> 
> I see that you have tried `build postbuild`, this would not build the types looking at the `development` branch (which you should be up to date with)
> 
> What should be done:
> 
> * run the workflow from your repo ensuring it completes without failure
> * verify the contents of the package via the `#code` tab on [npmjs](https://www.npmjs.com/package/@ubiquity-dao/rpc-handler?activeTab=code) and that they include `.d.ts` files then link us to the package
> 
> Thanks @Sadaf-A

Hey, I'm getting an auth error in GitHub Actions how can I test this?

**Comment by Keyrxng** [comment]
@Sadaf-A you would need to change the pkg name in `package.json` this should allow you to publish it to your own npmjs account (which should be deleted following the closure of this PR).

`@ubiquity-dao/rpc-handler` already exists, change to `@sadaf/qa-pkg` or something and set the action secrets needed for your repo and it should publish.

I checked your run logs and the issue is likely not having secrets set looking at it, although it could be the naming issue best to address both.

**Comment by Sadaf-A** [comment]
> @Sadaf-A you would need to change the pkg name in `package.json` this should allow you to publish it to your own npmjs account (which should be deleted following the closure of this PR).
> 
> `@ubiquity-dao/rpc-handler` already exists, change to `@sadaf/qa-pkg` or something and set the action secrets needed for your repo and it should publish.
> 
> I checked your run logs and the issue is likely not having secrets set looking at it, although it could be the naming issue best to address both.

Hey, I'm not able to run the workflow the error says you can't change the `yarn.lock` file

**Comment by Keyrxng** [comment]
Looking at your workflow runs we see that the attempt from your `development` branch did successfully build the package and it includes `.d.ts` files in the logged tarbell contents. 

The runs from your PR branch are failing because the workflow should not have the additional single `yarn` that you have added as the following yarn install is doing the same thing but with additional flags.

<hr/>

@0x4007 @rndquu I am not sure how to proceed with this PR because now that @Sadaf-A is up to date and has made a run from the development branch it has shown that no changes are required and the issue has been resolved via the current development branch build command which is `build: run-s clean build build:types`. What would you suggest? 

I've tried to avoid this from the jump but obviously I have approached it wrong, so I apologise for that @Sadaf-A.

**Comment by Sadaf-A** [comment]
> Looking at your workflow runs we see that the attempt from your `development` branch did successfully build the package and it includes `.d.ts` files in the logged tarbell contents. 
> 
> The runs from your PR branch are failing because the workflow should not have the additional single `yarn` that you have added as the following yarn install is doing the same thing but with additional flags.
> 
> <hr/>
> 
> @0x4007 @rndquu I am not sure how to proceed with this PR because now that @Sadaf-A is up to date and has made a run from the development branch it has shown that no changes are required and the issue has been resolved via the current development branch build command which is `build: run-s clean build build:types`. What would you suggest? 
> 
> I've tried to avoid this from the jump but obviously I have approached it wrong, so I apologise for that @Sadaf-A. 

Yeah, thats what I realised now the build command also handles types so there's no need to change the workflow. 
Thanks for your time

**Comment by rndquu** [comment]
I thinkg we should close this PR then (if this issue is already solved in the `development` branch) and mark https://github.com/ubiquity/rpc-handler/issues/21 as completed, @Keyrxng pls confirm

**Comment by Keyrxng** [comment]
I agree yes, the logs do contain types so no changes are required so this should be closed and the issue closed as complete. As for task reward I am not fussed either way. 

```bash
npm notice 942B    dist/types/constants.d.ts             
npm notice 541.3kB dist/types/dynamic.d.ts               
npm notice 1.8kB   dist/types/handler.d.ts               
npm notice 1.2kB   dist/types/rpc-handler.d.ts           
npm notice 2.5kB   package.json                          
npm notice === Tarball Details === 
npm notice name:          @ubiquity-dao/rpc-handler      
```

**Pull request closed without merging**
